INGENIC_VIDEOCAP_VERSION = master
INGENIC_VIDEOCAP_SITE = https://github.com/q09029/ingenic_videocap.git
INGENIC_VIDEOCAP_SITE_METHOD = git
INGENIC_VIDEOCAP_DEPENDENCIES =
INGENIC_VIDEOCAP_CONF_OPTS =

$(eval $(cmake-package))
